vertx-axle-clients/reactiverse-axle-postgres-client/pom.xml
vertx-axle-clients/vertx-axle-cassandra-client/pom.xml
vertx-axle-clients/vertx-axle-consul-client/pom.xml
vertx-axle-clients/vertx-axle-core/pom.xml
vertx-axle-clients/vertx-axle-kafka-client/pom.xml
vertx-axle-clients/vertx-axle-mail-client/pom.xml
vertx-axle-clients/vertx-axle-mongo-client/pom.xml
vertx-axle-clients/vertx-axle-rabbitmq-client/pom.xml
vertx-axle-clients/vertx-axle-redis-client/pom.xml
vertx-axle-clients/vertx-axle-web-client/pom.xml

Fix dependencies to avoid the class not found issue on TypeArg

---

vertx-axle-clients/vertx-axle-core/pom.xml
vertx-axle-clients/vertx-axle-core/src/test/java/io/vertx/it/CoreTest.java
vertx-axle-clients/vertx-axle-generator/pom.xml
vertx-axle-clients/vertx-axle-generator/src/main/java/io/vertx/lang/axle/AxleGenerator.java
vertx-axle-clients/vertx-axle-kafka-client/pom.xml
vertx-axle-clients/vertx-axle-kafka-client/src/test/java/io/vertx/axle/kafka/KafkaClientTest.java
vertx-axle-clients/vertx-axle-rabbitmq-client/pom.xml
vertx-axle-clients/vertx-axle-rabbitmq-client/src/test/java/io/vertx/axle/rabbitmq/RabbitMQClientTest.java

Generate toPublisherBuilder method

---

vertx-axle-clients/vertx-axle-generator/src/main/java/io/vertx/lang/axle/AbstractAxleGenerator.java
vertx-axle-clients/vertx-axle-generator/src/main/java/io/vertx/lang/axle/MappingIterator.java

Support Iterator, Iterable and Function API types

---

pom.xml
vertx-axle-clients/vertx-axle-amqp-client/src/test/java/io/vertx/axle/kafka/AMQPClientTest.java
vertx-axle-clients/vertx-axle-core/src/test/java/io/vertx/it/CoreTest.java
vertx-axle-clients/vertx-axle-generator/pom.xml
vertx-axle-clients/vertx-axle-kafka-client/src/test/java/io/vertx/axle/kafka/KafkaClientTest.java
vertx-axle-clients/vertx-axle-rabbitmq-client/src/test/java/io/vertx/axle/rabbitmq/RabbitMQClientTest.java

- Deactivated formatting for codegen module

Update to parent 7

---

vertx-axle-clients/vertx-axle-mysql-client/pom.xml
vertx-axle-clients/vertx-axle-mysql-client/src/test/java/io/vertx/axle/mysql/MySQLClientTest.java
vertx-axle-clients/vertx-axle-pg-client/pom.xml
vertx-axle-clients/vertx-axle-pg-client/src/test/java/io/vertx/axle/postgresql/PostGreSQLClientTest.java
vertx-axle-clients/vertx-axle-sql-client/pom.xml

* Fix the CI due to the wrong versions
* Fix the typo package name for Reactive PostgreSQL Client
* Add a test for Reactive MySQL Client

Reactive SQL Client improvements

---

vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/AbstractMutinyGenerator.java
vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/MutinyGenerator.java
vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/CodeGenHelper.java

Improve the javadoc of method returning Uni, and of "andAwait" / "andForget" methods.

Improve the Javadoc of the Mutiny generated client.

---

pom.xml

Update Vert.x to 3.9.2
Update Mutiny to 0.7.0

Update Vert.x version to 3.9.2 and Mutiny to 0.7.0

---

reactive-converters/readme.adoc

Small update in the README
Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

Update groupId in the Readme

---

.gitignore
vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/vertx/mutiny/test/EventbusTest.java

Add a test demonstrating how you consume from the event bus as a Multi.﻿

Add a test demonstrating how to consuming from the event bus as a multi

---

pom.xml
vertx-mutiny-clients/vertx-mutiny-amqp-client/src/test/java/io/vertx/mutiny/amqp/AMQPClientTest.java
vertx-mutiny-clients/vertx-mutiny-consul-client/src/test/java/io/vertx/mutiny/consul/ConsulClientTest.java
vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/AsyncVerticle.java
vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/vertx/mutiny/test/CoreTest.java
vertx-mutiny-clients/vertx-mutiny-db2-client/src/test/java/io/vertx/mutiny/db2/DB2ClientTest.java
vertx-mutiny-clients/vertx-mutiny-kafka-client/src/test/java/io/vertx/mutiny/kafka/KafkaClientTest.java
vertx-mutiny-clients/vertx-mutiny-mongo-client/src/test/java/io/vertx/mutiny/mongo/MongoClientTest.java
vertx-mutiny-clients/vertx-mutiny-pg-client/src/test/java/io/vertx/mutiny/postgresql/PostGreSQLClientTest.java
vertx-mutiny-clients/vertx-mutiny-rabbitmq-client/src/test/java/io/vertx/mutiny/rabbitmq/RabbitMQClientTest.java
vertx-mutiny-clients/vertx-mutiny-redis-client/src/test/java/io/vertx/mutiny/redis/RedisClientTest.java
vertx-mutiny-clients/vertx-mutiny-sql-client/src/main/java/io/vertx/mutiny/sqlclient/SqlClientHelper.java
vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/InTransactionMultiTest.java
vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/InTransactionUniTest.java
vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/SqlClientHelperTestBase.java

This pr contains two changesets:
- Update to Mutiny 0.8.0
- Use new Mutiny API idioms

update to mutiny 0.8.0

---

reactive-converters/converter-rxjava1/src/main/java/io/smallrye/reactive/converters/rxjava1/ObservableConverter.java

fix rxjava1.ObservableConverter#emitAtMostOneItem

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-auth-htdigest/pom.xml
vertx-mutiny-clients/vertx-mutiny-auth-htdigest/src/test/java/io/vertx/mutiny/auth/HtDigestAuthTest.java
vertx-mutiny-clients/vertx-mutiny-auth-htdigest/src/test/resources/.htdigest
vertx-mutiny-clients/vertx-mutiny-auth-jwt/pom.xml
vertx-mutiny-clients/vertx-mutiny-auth-oauth2/pom.xml
vertx-mutiny-clients/vertx-mutiny-bridge-common/pom.xml
vertx-mutiny-clients/vertx-mutiny-health-checks/pom.xml
vertx-mutiny-clients/vertx-mutiny-health-checks/src/test/java/io/vertx/mutiny/web/HealthCheckTest.java
vertx-mutiny-clients/vertx-mutiny-web-client/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-common/pom.xml
vertx-mutiny-clients/vertx-mutiny-web/pom.xml
vertx-mutiny-clients/vertx-mutiny-web/src/test/java/io/vertx/mutiny/web/RouterTest.java
vertx-mutiny-clients/vertx-mutiny-web/src/test/resources/assets/test.txt

- Add generation for the vertx-auth-htdigest module
- Add generation for the vertx bridge common module
- Extract vertx-web-common which was mixed with the web client
- Generate the mutiny variant of Vert.x Web
- Generate the mutiny variant of Vert.x health check

Add generation for Vert.x Web, Bridge Common, and Auth htdigest

---

vertx-mutiny-clients/pom.xml

* maven plugin and reported: 0.13.1
* java support: 0.23.1

Update revapi versions

---

pom.xml

[2.x] - Backport Bump smallrye-parent from 25 to 26

---

pom.xml

[2.x] Backport Bump jackson.version from 2.12.1 to 2.12.2

---

vertx-mutiny-clients/vertx-mutiny-kafka-client/pom.xml
vertx-mutiny-clients/vertx-mutiny-micrometer-metrics/pom.xml
vertx-mutiny-clients/vertx-mutiny-rabbitmq-client/pom.xml

[2.x] Backport Bump scala-reflect from 2.13.4 to 2.13.5

---

vertx-mutiny-clients/vertx-mutiny-runtime/src/main/java/io/smallrye/mutiny/vertx/AsyncResultUni.java
vertx-mutiny-clients/vertx-mutiny-runtime/src/main/java/io/smallrye/mutiny/vertx/MultiReadStream.java

Fix https://github.com/smallrye/smallrye-reactive-utils/issues/321

Fix missing decoration in the Uni and Multi implementations

---

vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/AwaitMethodGenerator.java
vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/ForgetMethodGenerator.java
vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/UniMethodGenerator.java

This allows re-enabling the openapi module

Handle method taking a Function returning a Future as parameter

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-mssql-client/pom.xml

Generate bindings for the MS SQL Client

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/website.yml
README.md
vertx-mutiny-clients/vertx-mutiny-auth-ldap/pom.xml

Configure Github Actions to build the project with Java 8, 11, 16 and 17-EA.﻿

Configure CI to build the project with  Java 8, 11, 16 and 17-EA

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-api-service/pom.xml

Add generation for the vertx-web-api-service module

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/website.yml
vertx-mutiny-clients/vertx-mutiny-pg-client/pom.xml

Also upgraded the CI matrix to 8/11/17.
Fixes #393

Use setup-java action caching

---

pom.xml

Supersedes #445 #446 #443 #444

Combined RevAPI upgrades

---

.github/workflows/build.yml
vertx-mutiny-clients-bom/pom.xml
vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-oracle-client/pom.xml

@cescoffier @jponge please review

Add Reactive Oracle Client

---

vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/MutinyMethodGenerator.java
vertx-mutiny-generator/src/tck/java/org/extra/JavadocTest.java

Fix javadoc issue when the method contain generics

---

vertx-mutiny-clients/vertx-mutiny-core/pom.xml

Reverts smallrye/smallrye-mutiny-vertx-bindings#534

Revert "Bump vertx-core from 4.2.7 to 4.3.0"

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-http-proxy/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-cookie-session-store/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-redis-session-store/pom.xml

Add the Vert.x HTTP proxy and the Vert.x Web Session stores (cookie and redis) modules

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-cookie-session-store/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-infinispan-session-store/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-redis-session-store/pom.xml

- Add the infinispan session store module
- Fix the module name of the redis and cookie session stores.

Add infinispan session store

---

vertx-mutiny-clients/vertx-mutiny-core/pom.xml

Align vert.x versions

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-web-proxy/pom.xml

Supersedes https://github.com/smallrye/smallrye-mutiny-vertx-bindings/pull/693.

Add vertx web proxy

---

vertx-mutiny-clients-bom/pom.xml

Add the Vert.x Http/Web Proxy modules in BOM

---

pom.xml
vertx-mutiny-clients/vertx-mutiny-core/pom.xml
vertx-mutiny-clients/vertx-mutiny-runtime/src/main/java/io/smallrye/mutiny/vertx/UniHelper.java
vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/UniMethodGenerator.java

- Bump vert.x version
- Fix generator to handle method receiving a Function<API, Future>

Update to Vert.x 4.4.0

---

pom.xml
vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/CodeGenHelper.java

Also handle the new Supplier of Future (Pool.java)

Update to Vert.x 4.4.2

---

.github/workflows/build.yml

- Remove Java 11
- Add Java 22

Change the Java versions used on the CI

---

.github/project.yml

This is to test the new release workflow.

Release version 3.15.2-RC1

---

vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/FunctionApplyMethodCodeWriter.java

Fix the return value in FunctionApplyMethodCodeWriter

---

pom.xml

Triggers using `-Dquickly`, as in:
./mvnw -Dquickly -T8

build: add a Maven quick build profile

---

vertx-mutiny-clients/pom.xml
vertx-mutiny-clients/vertx-mutiny-mail-client/pom.xml
vertx-mutiny-clients/vertx-mutiny-mail-client/src/test/java/io/vertx/mutiny/mail/MailClientTest.java
vertx-mutiny-code-generator/src/main/java/io/smallrye/mutiny/vertx/apigenerator/JavadocHelper.java
vertx-mutiny-code-generator/src/main/java/io/smallrye/mutiny/vertx/apigenerator/shims/UniMethodShimModule.java

Handle void in Javadoc's return tag

---

pom.xml

This is a patch release with bug fixes.

Bump to Mutiny 2.9.3
