smallrye/smallrye-mutiny-vertx-bindings

- pom.xml
- vertx-axle-clients/vertx-axle-generator/src/main/java/io/vertx/lang/axle/AbstractAxleGenerator.java
- vertx-axle-clients/vertx-axle-generator/src/test/java/io/vertx/lang/axle/test/ReadStreamAdapterBackPressureTest.java
This PR:
1. Updates the Vert.x version to 3.8.1
2. Contains a fix for #63 - based on the fix made in Vert.x RX
3. Contains a fix for #39 updating the read stream tests as `FakeStream` has changed
> Update to vertx 3.8.1

- vertx-axle-clients/vertx-axle-core/pom.xml
- vertx-mutiny-clients/vertx-mutiny-core/pom.xml
The reason for this removal is the following:
A security vulnerability, CVE-2019-17571 has been identified against Log4j 1. Log4j includes a SocketServer that accepts serialized log events and deserializes them without verifying whether the objects are allowed or not. This can provide an attack vector that can be exploited. Since Log4j 1 is no longer maintained, this issue will not be fixed.
log4j 1 was only included for the Log facade. As this log facade is not involved during the generation and is not shipped with the generated API, this removal is harmless.
> Remove the dependency on log4j version 1

- vertx-mutiny-clients/vertx-mutiny-core/pom.xml
- vertx-mutiny-clients/vertx-mutiny-core/src/main/java/io/smallrye/mutiny/vertx/core/AbstractVerticle.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/AbstractVerticleTest.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/AsyncVerticle.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/SyncVerticle.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/VerticleFailingAsynchronously.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/VerticleFailingAsynchronouslyOnStop.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/VerticleFailingSynchronously.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/verticle/VerticleFailingSynchronouslyOnStop.java
Fix https://github.com/smallrye/smallrye-reactive-utils/issues/109.
Implement a Mutiny version of AbstractVerticle
It provides a version of AbstractVerticle allowing the user to return `Uni` instances for the start and stop callbacks (`asyncStart` and `asyncStop` methods).
> Implement a Mutiny version of AbstractVerticle

- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/vertx/mutiny/test/CoreTest.java
The core API test for WebSocket is incorrect as it doesn't call subscribe when sending the pong message reply to the client.
> Fix incorrect WebSocket test

- pom.xml
- vertx-mutiny-clients/vertx-mutiny-runtime/src/main/java/io/smallrye/mutiny/vertx/AsyncResultUni.java
- Update to Mutiny 0.14.0
- Update to RX Java 2.2.21
- Update to Reactor Core 3.4.3
- Update test containers to 1.15.2
> Upgrade to Mutiny 0.14.0

- pom.xml
> [2.x] Bump rxjava from 3.0.10 to 3.0.11

- vertx-mutiny-clients/pom.xml
> [2.x] Backport Bump revapi-maven-plugin from 0.12.2 to 0.13.4

- vertx-mutiny-clients/vertx-mutiny-core/pom.xml
> [2.x] Backport Bump log4j-api from 2.13.3 to 2.14.1

- vertx-mutiny-clients/vertx-mutiny-rabbitmq-client/pom.xml
Fix https://github.com/smallrye/smallrye-reactive-utils/issues/293.
> Remove dependency on Zookeeper and Scala in the RabbitMQ client.

- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySQLClientTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySqlInTransactionMultiTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySqlInTransactionUniTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySqlUsingConnectionSafetyTest.java
- vertx-mutiny-clients/vertx-mutiny-pg-client/src/test/java/io/vertx/mutiny/postgresql/PgInTransactionMultiTest.java
- vertx-mutiny-clients/vertx-mutiny-pg-client/src/test/java/io/vertx/mutiny/postgresql/PgInTransactionUniTest.java
- vertx-mutiny-clients/vertx-mutiny-pg-client/src/test/java/io/vertx/mutiny/postgresql/PgUsingConnectionSafetyTest.java
- vertx-mutiny-clients/vertx-mutiny-pg-client/src/test/java/io/vertx/mutiny/postgresql/PostGreSQLClientTest.java
- vertx-mutiny-clients/vertx-mutiny-sql-client/src/main/java/io/vertx/mutiny/sqlclient/SqlClientHelper.java
- vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/SqlClientHelperTestBase.java
- vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/TransactionMultiTest.java
- vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/TransactionUniTest.java
- vertx-mutiny-clients/vertx-mutiny-sql-client/src/test/java/io/vertx/mutiny/sqlclient/UsingConnectionSafetyTest.java
Related to https://github.com/quarkusio/quarkus/issues/16430
When a problem occurs on the DB side (e.g. constraint violation), the SqlClientHelper implementation must convey the original error message to the user.
Also, in order to avoid a redundant call to the SqlClient#rollback, we can check if the failure is a TransactionRollbackException.
> SqlClientHelper: fix transaction management

- pom.xml
- vertx-mutiny-clients/pom.xml
- vertx-mutiny-clients/vertx-mutiny-auth-sql-client/src/test/java/io/smallrye/mutiny/vertx/auth/AuthSqlClientTest.java
- vertx-mutiny-clients/vertx-mutiny-cassandra-client/src/test/java/io/vertx/mutiny/cassandra/CassandraClientTest.java
- vertx-mutiny-clients/vertx-mutiny-consul-client/src/test/java/io/vertx/mutiny/consul/ConsulClientTest.java
- vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/MutinyGenerator.java
- vertx-mutiny-clients/vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/CodeGenHelper.java
- vertx-mutiny-clients/vertx-mutiny-mongo-client/src/test/java/io/vertx/mutiny/mongo/MongoClientTest.java
- vertx-mutiny-clients/vertx-mutiny-mqtt/src/test/java/io/vertx/mutiny/mqtt/MqttClientTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySQLClientTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySqlInTransactionMultiTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySqlInTransactionUniTest.java
- vertx-mutiny-clients/vertx-mutiny-mysql-client/src/test/java/io/vertx/mutiny/mysql/MySqlUsingConnectionSafetyTest.java
- vertx-mutiny-clients/vertx-mutiny-rabbitmq-client/src/test/java/io/vertx/mutiny/rabbitmq/RabbitMQClientTest.java
- vertx-mutiny-clients/vertx-mutiny-redis-client/src/test/java/io/vertx/mutiny/redis/RedisClientTest.java
Update to Vert.x 4.1.0.CR2
* fix code generator when a function does not expect the result to be a translated type
* disable vertx-mutiny-web-openapi - need to be investigated
> update to vertx 4.1.0.CR2

- .build/render-documentation.sh
- .github/workflows/build.yml
- .github/workflows/release.yml
- pom.xml
- vertx-mutiny-clients-bom/pom.xml
- Bump to Mutiny 0.19.2
- Isolate the BOM
- Also update the release version in submodules
> Mutiny 0.19.2 and BOM isolation

- pom.xml
- vertx-mutiny-clients/vertx-mutiny-junit5/pom.xml
With the new parent, junit and friends ended up in the compile scope which leaks to the classpath.
> Fix test dependency scope

- vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/ImportDeclarationCodeWriter.java
The Publisher and Subscriber classes do not need to be imported as it use the fully qualified class name in the generated code.
Fix #492.
> Remove unused imports in the generated classes

- vertx-mutiny-clients-bom/pom.xml
This is probably an oversight but just in case, to make it a valid constraint `<type>pom</type>` would have to be added. But given that dependencies on this POM are unlikely, it could simply be removed.
> Remove non-existing vertx-mutiny-clients jar from the BOM

- pom.xml
- vertx-mutiny-clients/vertx-mutiny-web-client/pom.xml
which revert the close method signature change.
> Update the Web Client to 4.3.2.1 

- .github/project.yml
- Bump vertx-core from 4.3.2 to 4.3.3
- Remove the specific version for Vert.x Web 4.2.3.1
- Update compatibility report documentation
- Update containers to work on ARM and AMD.
- Bump maven-javadoc-plugin from 3.4.0 to 3.4.1
- Prepare the 2.26.0 release
> prepare release 2.26.0

- vertx-mutiny-clients-bom/pom.xml
This PR adds 3 missing clients to BOM. 
`smallrye-mutiny-vertx-db2-client` `smallrye-mutiny-vertx-web-api-service` `smallrye-mutiny-vertx-uri-template`
> Added missing vertx-mutiny-clients to BOM

- pom.xml
Update various dependencies:
- update Vert.x to version 4.3.5
- update Mutiny to version 1.8.0
- update Jackson to version 2.14.0
- update Reactor Core to version 3.5.0
> Update Vertx to 3.4.5 and Mutiny to 1.8.0

- vertx-mutiny-clients/vertx-mutiny-uri-template/pom.xml
Fix https://github.com/smallrye/smallrye-mutiny-vertx-bindings/issues/694
> Fix module name of the URI template module

- .gitignore
- pom.xml
Because of https://github.com/FasterXML/jackson-core/issues/1027.
> Rollback jackson update

- pom.xml
This does not require a release as the upgrade from 2.4.0 to 2.5.0 is transparent.
> Mutiny 2.5.0

- pom.xml
- vertx-mutiny-clients/pom.xml
- vertx-mutiny-clients/vertx-mutiny-camel-bridge/pom.xml
- vertx-mutiny-clients/vertx-mutiny-web-api-contract/pom.xml
- vertx-mutiny-clients/vertx-mutiny-web-templ-httl/pom.xml
- vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/lang/ImportDeclarationCodeWriter.java
- vertx-mutiny-generator/src/tck/java/io/vertx/core/streams/Pump.java
- Bump to Vert.x 4.5.1
- Add generation for the Vert.x Camel Bridge
- Add generation for the Vert.x Web API Contract module
- Add generation for the Vert.x Web HTTL template engine
| `method io.smallrye.mutiny.Uni<io.vertx.mutiny.redis.client.Response> io.vertx.mutiny.redis.client.RedisAPI::pfdebug(java.util.List<java.lang.String>)` a| 
* Source: BREAKING 
* Binary: BREAKING | error | The number of parameters of the method have changed.
| `method io.vertx.mutiny.redis.client.Response io.vertx.mutiny.redis.client.RedisAPI::pfdebugAndAwait(java.util.List<java.lang.String>)` a| 
* Source: BREAKING 
* Binary: BREAKING | error | The number of parameters of the method have changed.
| `method io.vertx.mutiny.redis.client.RedisAPI io.vertx.mutiny.redis.client.RedisAPI::pfdebugAndForget(java.util.L …
> Bump to Vert.x 4.5.1

- pom.xml
The only detected breaking changes are related to the vertx-mutiny-http-proxy module.
Full release notes are there: https://github.com/vert-x3/wiki/wiki/4.5.3-Release-Notes. Note that this new version contains a CVE fix.
> Update Vert.x to version 4.5.3

- pom.xml
Full release notes are there: https://github.com/vert-x3/wiki/wiki/4.5.4-Release-Notes.
> Update Vert.x to version 4.5.4

- pom.xml
- vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/MutinyMethodDescriptor.java
Full release notes are there: https://github.com/vert-x3/wiki/wiki/4.5.5-Release-Notes.
Also work around the deprecation of some of the executeBlocking signatures.
> Update Vert.x to version 4.5.5

- .github/project.yml
The main change is the update to Vert.x 4.5.5 (https://github.com/vert-x3/wiki/wiki/4.5.5-Release-Notes)
Also work around the deprecation of some of the executeBlocking signatures.
> Prepare release 3.11.0

- pom.xml
Potentially breaking change:
Element | Classification | Criticality | Description
-- | -- | -- | --
class io.vertx.mutiny.ext.auth.VertxContextPRNG | Source: POTENTIALLY_BREAKINGBinary: POTENTIALLY_BREAKING | error | Non-final class now inherits from 'io.vertx.mutiny.ext.auth.prng.VertxContextPRNG'.
Also, it is still not possible to update to Micrometer 1.13.x
> Bump Vert.x to 4.5.10

- vertx-mutiny-clients/vertx-mutiny-micrometer-metrics/pom.xml
This reverts commit d9ed655ec9fc38a9f928c8d6f879f014e760ba3c.
> Revert "Bump micrometer.version from 1.12.5 to 1.13.6"

- .github/project.yml
- vertx-mutiny-clients-bom/pom.xml
- **Set the deploy plugin version for the BOM module**
- **Release 3.15.2-RC2**
> Release 3.15.2 RC2

- docs/using-vertx-expectations.md
- vertx-mutiny-clients/vertx-mutiny-core/src/main/java/io/smallrye/mutiny/vertx/core/Expectations.java
- vertx-mutiny-clients/vertx-mutiny-core/src/test/java/io/smallrye/mutiny/vertx/core/ExpectationsTest.java
> Support for Vert.x expectations as pluggable operators

- pom.xml
Also fixes CycloneDX not heing skipped in quick builds.
> fix: switch to the correct Jandex Maven plugin

- vertx-mutiny-clients-bom/pom.xml
- vertx-mutiny-clients/pom.xml
- vertx-mutiny-clients/vertx-mutiny-openapi/pom.xml
- vertx-mutiny-clients/vertx-mutiny-web-openapi-router/pom.xml
- vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/MutinyGenerator.java
- vertx-mutiny-generator/src/main/java/io/smallrye/mutiny/vertx/codegen/methods/UniMethodGenerator.java
- vertx-mutiny-generator/src/tck/java/org/extra/StaticMethodWithFuture.java
- vertx-mutiny-generator/src/test/java/tck/StaticMethodsTest.java
Closes #920
Original PR https://github.com/smallrye/smallrye-mutiny-vertx-bindings/pull/926 by @pk-work was reverted because the generator does not support static method returning futures (see https://github.com/smallrye/smallrye-mutiny-vertx-bindings/issues/920#issuecomment-2158853882)
This PR adds support for such methods and brings back Vert.x OpenAPI and Web OpenAPI Router bindings.
> Add bindings for Vert.x OpenAPI and Web OpenAPI Router
